TrajectoryGAN:
    SavingPoint: trained_models/trajectory-gan.pt
    Embedding:
    - 8
    - 16
    GeneratorLSTM: 62
    DiscriminatorLSTM: 62
    GeneratorHidden:
    - 64
    - 32
    DiscriminatorHidden:
    - 64
    - 32
    LeakyRelu: 0.1
    BaseDistrDim: 2
    ImprovedDiscriminator: 10
    NumEpoch: 2001
    BatchSize: 128
    GeneratorLearning: 0.001
    DiscriminatorLearning: 0.001
    Beta1: 0.9
    Beta2: 0.999

Logger: /../debug/log.txt
